import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useMemo, useState } from "react";
import { Bell, Trash2 } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { notifications } from "@/lib/api/resources";

export const Route = createFileRoute("/notifications")({ component: NotificationsPage });
function NotificationsPage() {
  const client = useQueryClient(); const query = useQuery({ queryKey: ["notifications"], queryFn: notifications.list }); const [filter, setFilter] = useState("All"); const [page, setPage] = useState(1); const pageSize = 8;
  const filtered = useMemo(() => (query.data ?? []).filter((item) => filter === "All" || (filter === "Unread" ? item.status !== "Read" : item.notification_type.toLowerCase().includes(filter.toLowerCase()))), [filter, query.data]); const pages = Math.max(1, Math.ceil(filtered.length / pageSize)); const visible = filtered.slice((page - 1) * pageSize, page * pageSize);
  const act = async (request: Promise<unknown>, message: string) => { try { await request; toast.success(message); await client.invalidateQueries({ queryKey: ["notifications"] }); } catch { toast.error("Unable to update notification."); } };
  return <main className="mx-auto w-full max-w-7xl space-y-6 px-5 py-8 lg:px-8"><header className="flex items-center gap-4"><span className="grid size-10 place-items-center rounded-md bg-jade/10 text-jade"><Bell className="size-5" /></span><div><h1 className="font-display text-2xl font-semibold">Notifications</h1><p className="mt-1 text-sm text-muted-foreground">Filter and resolve important contract workspace alerts.</p></div></header><section className="rounded-lg bg-card shadow-hairline"><div className="flex flex-wrap gap-2 border-b border-border p-4">{["All", "Unread", "Important", "Contract", "Renewal", "Compliance"].map((item) => <Button key={item} size="sm" variant={filter === item ? "default" : "outline"} onClick={() => { setFilter(item); setPage(1); }}>{item}</Button>)}</div>{query.isLoading ? <p className="p-8 text-sm text-muted-foreground">Loading notifications…</p> : <div className="divide-y divide-border/60">{visible.map((item) => <article key={item.id} className="flex flex-col gap-3 p-4 sm:flex-row sm:items-start"><div className={`mt-1 size-2 shrink-0 rounded-full ${item.status === "Read" ? "bg-muted" : "bg-jade"}`} /><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h2 className="font-medium">{item.title}</h2><Badge variant={item.status === "Read" ? "secondary" : "default"}>{item.status}</Badge><Badge variant="outline">{item.notification_type}</Badge></div><p className="mt-1 text-sm text-muted-foreground">{item.message}</p><p className="mt-2 text-xs text-muted-foreground">{new Date(item.created_at).toLocaleString()}</p></div><div className="flex gap-1">{item.status !== "Read" ? <Button size="sm" variant="outline" onClick={() => act(notifications.markRead(item.id), "Notification marked read")}>Mark read</Button> : null}<Button size="icon" variant="ghost" title="Delete notification" onClick={() => act(notifications.delete(item.id), "Notification deleted")}><Trash2 className="size-4 text-destructive" /></Button></div></article>)}</div>}{!query.isLoading && !visible.length ? <p className="p-10 text-center text-sm text-muted-foreground">No notifications match this filter.</p> : null}<div className="flex items-center justify-between border-t border-border p-4 text-sm"><span className="text-muted-foreground">Page {page} of {pages}</span><div className="flex gap-2"><Button size="sm" variant="outline" disabled={page <= 1} onClick={() => setPage((value) => value - 1)}>Previous</Button><Button size="sm" variant="outline" disabled={page >= pages} onClick={() => setPage((value) => value + 1)}>Next</Button></div></div></section></main>;
}
