import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { CircleUserRound } from "lucide-react";
import { toast } from "sonner";
import { Avatar, AvatarFallback, AvatarImage } from "@/components/ui/avatar";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { users } from "@/lib/api/resources";
import { useAuth } from "@/lib/auth/auth-context";

export const Route = createFileRoute("/profile")({ component: Profile });
function Profile() {
  const { user } = useAuth(); const client = useQueryClient(); const profile = useQuery({ queryKey: ["users", user?.id], queryFn: () => users.get(user!.id!), enabled: Boolean(user?.id) }); const [editing, setEditing] = useState(false); const [busy, setBusy] = useState(false);
  if (profile.isLoading) return <main className="mx-auto max-w-3xl px-5 py-8 text-sm text-muted-foreground">Loading profile…</main>;
  if (!profile.data) return <main className="mx-auto max-w-3xl px-5 py-8 text-sm text-destructive">Unable to load your profile.</main>;
  const item = profile.data; const initials = item.full_name.split(" ").map((part) => part[0]).join("").slice(0, 2).toUpperCase();
  const save = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setBusy(true); const form = new FormData(event.currentTarget); try { await users.update(item.id, { full_name: form.get("full_name"), email: form.get("email"), password: form.get("password") || undefined, avatar_url: form.get("avatar_url") || undefined, preferences: { compact_mode: form.get("compact_mode") === "on", email_alerts: form.get("email_alerts") === "on" } }); await client.invalidateQueries({ queryKey: ["users", item.id] }); setEditing(false); toast.success("Profile updated"); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to update profile."); } finally { setBusy(false); } };
  return <main className="mx-auto w-full max-w-3xl space-y-6 px-5 py-8 lg:px-8"><header className="flex items-center gap-4"><span className="grid size-10 place-items-center rounded-md bg-jade/10 text-jade"><CircleUserRound className="size-5" /></span><div><h1 className="font-display text-2xl font-semibold">Profile</h1><p className="mt-1 text-sm text-muted-foreground">Manage identity, security, avatar, and workspace preferences.</p></div></header><section className="rounded-lg bg-card p-6 shadow-hairline"><div className="flex items-center gap-4"><Avatar className="size-16"><AvatarImage src={item.avatar_url ?? undefined} /><AvatarFallback className="text-lg">{initials}</AvatarFallback></Avatar><div><h2 className="font-display text-lg font-semibold">{item.full_name}</h2><p className="text-sm text-muted-foreground">{item.email}</p><p className="mt-1 text-xs text-jade">{item.role} · {item.is_active ? "Active" : "Inactive"}</p></div><Button className="ml-auto" variant="outline" onClick={() => setEditing((value) => !value)}>{editing ? "Cancel" : "Edit profile"}</Button></div>{editing ? <form className="mt-6 grid gap-4 sm:grid-cols-2" onSubmit={save}><Field name="full_name" label="Full name" defaultValue={item.full_name} /><Field name="email" label="Email" type="email" defaultValue={item.email} /><Field name="password" label="New password" type="password" required={false} defaultValue="" /><Field name="avatar_url" label="Avatar URL" required={false} defaultValue={item.avatar_url ?? ""} /><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="email_alerts" defaultChecked={Boolean(item.preferences?.email_alerts ?? true)} />Email alerts</label><label className="flex items-center gap-2 text-sm"><input type="checkbox" name="compact_mode" defaultChecked={Boolean(item.preferences?.compact_mode)} />Compact workspace</label><Button type="submit" disabled={busy} className="sm:col-span-2">{busy ? "Saving…" : "Save profile"}</Button></form> : <dl className="mt-6 grid gap-4 border-t border-border pt-5 text-sm sm:grid-cols-2"><Detail label="Last login" value={item.last_login ? new Date(item.last_login).toLocaleString() : "Never"} /><Detail label="Account created" value={item.created_at ? new Date(item.created_at).toLocaleDateString() : "—"} /><Detail label="Preferences" value={item.preferences?.email_alerts === false ? "Email alerts off" : "Email alerts on"} /></dl>}</section></main>;
}
function Field({ name, label, defaultValue, type = "text", required = true }: { name: string; label: string; defaultValue: string; type?: string; required?: boolean }) { return <label className="space-y-2 text-sm"><Label>{label}</Label><Input name={name} type={type} defaultValue={defaultValue} required={required} /></label>; }
function Detail({ label, value }: { label: string; value: string }) { return <div><dt className="text-muted-foreground">{label}</dt><dd className="mt-1 font-medium">{value}</dd></div>; }
