import { createFileRoute } from "@tanstack/react-router";
import { useQuery, useQueryClient } from "@tanstack/react-query";
import { useState } from "react";
import { BarChart3, Download, FileBarChart2, FileCheck2, FileClock, FileText, ShieldCheck } from "lucide-react";
import { toast } from "sonner";
import { Button } from "@/components/ui/button";
import { reports, reportFiles } from "@/lib/api/resources";
import type { Report } from "@/lib/api/types";

export const Route = createFileRoute("/reports")({ component: ReportsPage });
const reportTypes = [
  { type: "Compliance Report", label: "Compliance report", description: "Risk scores, compliance status, and obligation health.", icon: ShieldCheck },
  { type: "Renewal Report", label: "Renewal report", description: "Upcoming, in-progress, renewed, and expired renewals.", icon: FileClock },
  { type: "Contract Report", label: "Contract report", description: "Contract portfolio and lifecycle status.", icon: FileText },
  { type: "Obligation Report", label: "Obligation report", description: "Deadlines, priorities, and completion status.", icon: FileCheck2 },
  { type: "Audit Report", label: "Audit report", description: "Recorded operational audit events.", icon: BarChart3 },
];

function ReportsPage() {
  const client = useQueryClient(); const [busy, setBusy] = useState<string | null>(null); const list = useQuery({ queryKey: ["reports"], queryFn: reports.list });
  const generate = async (type: string) => { setBusy(type); try { await reports.create({ report_name: type.replace(" Report", ""), report_type: type }); await client.invalidateQueries({ queryKey: ["reports"] }); toast.success(`${type} generated`); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to generate report."); } finally { setBusy(null); } };
  const download = async (report: Report) => { try { const url = await reportFiles.download(report.id); const anchor = document.createElement("a"); anchor.href = url; anchor.download = `${report.report_name}.json`; anchor.click(); URL.revokeObjectURL(url); } catch (error) { toast.error(error instanceof Error ? error.message : "Unable to download report."); } };
  return <main className="mx-auto w-full max-w-7xl space-y-6 px-5 py-8 lg:px-8"><header className="flex items-start gap-4"><span className="grid size-10 place-items-center rounded-md bg-jade/10 text-jade"><FileBarChart2 className="size-5" /></span><div><h1 className="font-display text-2xl font-semibold">Reports</h1><p className="mt-1 text-sm text-muted-foreground">Generate and download operational compliance reports.</p></div></header><section className="grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{reportTypes.map((item) => <div key={item.type} className="rounded-lg bg-card p-5 shadow-hairline"><item.icon className="size-5 text-jade" /><h2 className="mt-4 font-display text-sm font-semibold">{item.label}</h2><p className="mt-1 min-h-10 text-sm text-muted-foreground">{item.description}</p><Button className="mt-4" size="sm" onClick={() => generate(item.type)} disabled={busy !== null}><BarChart3 className="mr-2 size-4" />{busy === item.type ? "Generating…" : "Generate"}</Button></div>)}</section><section className="space-y-3"><h2 className="font-display text-sm font-semibold">Generated reports</h2>{list.data?.length ? list.data.map((report) => <article key={report.id} className="flex flex-col gap-3 rounded-lg bg-card p-4 shadow-hairline sm:flex-row sm:items-center sm:justify-between"><div><p className="font-medium">{report.report_name}</p><p className="text-xs text-muted-foreground">{report.report_type} · generated by user {report.generated_by}</p></div><Button size="sm" variant="outline" onClick={() => download(report)}><Download className="mr-2 size-4" />Download</Button></article>) : <div className="rounded-lg border border-dashed border-border p-10 text-center text-sm text-muted-foreground">No reports generated yet.</div>}</section></main>;
}
